### ISSUE TITLE
Implement an MMU for the imsaisim

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#68]
I would like to implement an MMU for the **imsaisim** machine to enable a banked implementation of CP/M 3 (plus).
It seems straight forward to use the same "design" as for the **cpmsim** machine, but I have a few considerations and a few questions.

On the ESP32 port, the extra RAM (4MB PSRAM) is not as fast as the internal RAM (it is SPI connected through a 32K cache). I have done some testing using 64K reserved in the internal RAM, and copying (`memcpy`) the current segment out to SPRAM and the new segment in from SPRAM. The one advantage of this strategy is that the existing memory implementation doesn't need to be modified, but it has a time cost.

Timing is a follows:

Segment size | Time to "switch" 
------------- | ---------------
16K | 1.4ms
32K | 3.2ms
48K | 5.4ms

Its not linear because of the 32K cache.

### Question 1:
Do you think the above timings for bank switching are acceptable, or do you think they will have a big impact on performance?

### Question 2: 
Is it OK to still use I/O ports 20-23, it looks like some are reserved because of a missing parallel port peripheral. If new ports need to be allocated what would you recommend?

**Comment by EtchedPixels** [comment]
There are pathalogical cases but not many.

However the hot area of a Z80 system running CP/M is under 32K so the cache will give you perfectly good performance anyway and it seems to me overcomplicated. With CP/M 3 for example if your banked BDOS is in PSRAM it's total footprint is under 32K anyway so you'll just run out of cache all the time except if you have a ramdisc and that might cause some evictions but no big deal.

MP/M you'd get some cache evictions but I'd bet even then it would behave perfectly fine.

In the FPGA world socz80 runs a 128MHz T80 core to SDRAM backed by a 16K direct mapped cache (is as primitive a cache policy as it gets). It runs near enough the full expected 128MHz speed all the time because of the locality of reference. I'd say the evidence says don't worry 8)

Another way of looking at it - the ESP32 is doing in hard logic at a finer granularity what you plan to do in software!

There is only one true MMU port for S100 - 0x40 8)

**Comment by udo-munk** [comment]
In releases < 1.31 the banking was implemented by copying the 48KB banks into the 64KB address space of the CPU. Even on fast systems with memcpy() assembler implementations this is awfull slow, and CP/M 3 does a lot of unnecessary calls to the bank switch routine. With hardware that doesn't matter because it happens in a few microseconds, but with memcpy() that needs milliseconds the performace is really bad.
I agree with Alan, lets put additional 48KB banks in the SPI RAM and have the cache logic deal with it.

The cpmsim MMU is overly complex because I used it as a playground for experiments. One single port, perhaps 0x40, that gets the bank number 0-7 for the lower 48KB bank is good enough for everything. OK, maybe Alan wants 16 banks for FUZIX ;-), the DRI OS's only support max 8 memory segments.

**Comment by udo-munk** [comment]
Read a bit through documentation for large S100 bus memory cards. The usual configuration is 16KB common + n banks 48KB. The banks are selected with a bit in a I/O register (0x40) like this:

1 = system bank
2 = user bank 1
4 = user bank 2
8 = user bank 3
16 = user bank 4
32 = user bank 5
64 = user bank 6
128 = user bank 7

Every other value disables all memory, so the CPU would always read 0xff and loop forever. So in emulation this should be a fatal error and stop everything.

Would be very easy to implement too.

**Comment by EtchedPixels** [comment]
@udo-munk  I thought MP/M supported up to 2MB RAM ?

Over 512K is fairly pointless even with Fuzix. I have 4MB in my ZX Evolution and no idea what to use it for 8)

On the MMU side the other MMU form you see on some of the CPU cards is a latch that provides A16-A23 on the bus. That's what I implemented on my 8085 CPU card for RC2014 bus.

**Comment by dmcnaugh** [comment]
My further research shows another variation:

http://www.s100computers.com/My%20System%20Pages/MEM8Plus/MEM8Plus%20Board.htm

Two possible bank select modes are supported (dip switch selectable):
1. (similar to Udo's comment, but) 4 banks using 3 bits - named "Cromemco" mode
  - 0 = system bank
  - 1 = user bank 1
  - 2 = user bank 2
  - 4 = user bank 3
2. regular sequential numbering up to 16 banks (not really 1MB if you are only switching 48K banks)

This board also supports the A16-A23 mode addressing, but I don't imagine this works for CP/M as it wouldn't provide a common segment, but maybe useful for some other OSs.

The CP/M 3 (plus) System Guide mentions that it supports up to 16 banks, but I fail to see that more than 3  banks would be useful to CP/M 3.

The complexity with implementing banked RAM on the ESP32 comes from its memory caching, the 32K of system managed cache is shared between the first 4MB of PSRAM and the program flash, so there will be contention from both sides, data and code. There is another API called **himem** for accessing the other spare 4MB of PSRAM, and it looks like you can reserve your own cache in 32K increments then bank switch blocks of this size through this cache. So I would just work with full 64K blocks and not use the top 16K that is mapped as the common segment (its not like I'll run out of PSRAM, and that chip cost $1.80. Actually I could support 64 x 64K banks and still only be using half the total PSRAM!) but use a seperate 16K somewhere in internal RAM for that. I'll give this a go and see if I can detect any performance hit.

**Comment by EtchedPixels** [comment]
Back in the old days you'd have a 16K RAM card that ignored A16-A23 jumpered for C000-FFFF and a bunch of 48K or similar cards for the other banks that didn't. The latch would effectively bank switch the low 48K only. It wasn't as if you could fit 512K of 16Kx1 DRAMs on a board.

Cromemco are the folks who popularised the 0x40 and one bit per bank.

It's only 75 clocks @ 80MHz to load a cache line to load a cache line (32 bytes) so I would be very surprised if it makes any difference, and if it does you can move the critical bits of code to iram.

It's not like a real Z80 could copy memory at more than about 13 clocks/byte 8)

**Comment by udo-munk** [comment]
MP/M supports 512KB, 8 memory segments. I thought about increasing that, but it's hardcoded all over the place and would be quite some work. With a 4 or 6 MHz CPU supporting 7 users with an OS is the practical limit, supporting more users requires a significantely faster CPU. No problem with the PC emulations, but what for?

Right, CP/M 3 supports 16 memory segments, so up to 1MB. On systems with mechanical disk systems you want every bit of memory you can get, the LRU cache implementation from DRI is quite good and mighty improves throughput. With regrads to CP/M the largest systems we build back then had 512KB memory, but that was due to costs and number of boards needed, would have loved to build one with 1MB ;-)

So I would like 8 memory segments at least, so that we also can implement MP/M and FUZIX on the machine. More is not necessary, without using mechanicals disks a larger cache won't improve throughput any further.

I don't really care if the banking logic uses the Cromemco 1 bit/bank, or a sequential number. Both was done and I see no cons/pros for any of this implementations.

I would suggest to use 48KB and not full 64KB banks. In the 8080esp it doesn't matter, in the PC emulations it would waste a bit of memory.

**Comment by udo-munk** [comment]
I have implemented a MMU with 7 additional 48KB memory segments. Bank select is via port 64 (0x40) with a bank number 0-7.

**Comment by udo-munk** [comment]
I can confirm that the implemented banked memory is working OK:

A>b:cpmldr

CP/M V3.0 Loader
Copyright (C) 1998, Caldera Inc.    

 BNKBIOS3 SPR  ED00  0300
 BNKBIOS3 SPR  BE00  0200
 RESBDOS3 SPR  E700  0600
 BNKBDOS3 SPR  9000  2E00
 
 57K TPA

IMSAI 8080 banked BIOS V1.0,
Copyright (C) 2019, Udo Munk
A>dir
A: CPM3     SYS : CCP      COM : PIP      COM : GET      COM : PUT      COM 
A: SET      COM : SUBMIT   COM : DUMP     COM : SHOW     COM : SAVE     COM 
A: DATE     COM : SID      COM : HELP     COM : HELP     HLP : DIR      COM 
A: TYPE     COM : ED       COM : HEXCOM   COM : ERASE    COM : SETDEF   COM 
A: DEVICE   COM : RENAME   COM : GENCOM   COM : HIST     UTL : TRACE    UTL 
A: BYE      COM 
A>dir b:
B: COPYSYS  COM : INITDIR  COM : PATCH    COM : GENCPM   COM : CPM3     SYS 
B: CPMLDR   COM : CPMLDR   REL : BNKBIOS3 SPR : RESBDOS3 SPR : BDOS3    SPR 
B: BNKBDOS3 SPR : BOOT     PRN : BNKBIOS3 PRN : LDRBIOS  PRN : SCB      PRN 
B: BNKBIOS3 ASM : LDRBIOS  REL : BOOT     HEX : MAC      COM : RMAC     COM 
B: LINK     COM : WM-ANSI  COM : WM       HLP : BOOT     ASM : BOOT     SYM 
B: CPMLDR   SYM : LDRBIOS  ASM : LDRBIOS  SYM : BNKBIOS3 REL : LDR      SUB 
B: BNKBIOS3 SYM : GENCPM   DAT : SCB      REL : SCB      SYM : SCB      ASM 
B: SYSGEN   SUB 
A>show

A: RW, Space:        19k
B: RW, Space:        11k


A>
A>date
Wed 12/15/1982 00:00:00
A>

I will need a bit to clean up the BIOS's and everything before release.

**Comment by dmcnaugh** [comment]
Great,
I've tested this and it works on my implementation for the ESP32 port.
The ESP32 implementation has the same "interface" ie. port 0x40 but because I wrote it before you posted your version, the implementation is slightly different. I reload the `wrtvec` and `rdrvec` vector tables on each bank switch. Makes a bank switch take a little longer, but makes each memory access (R or W) the same.

I notice that it is just using banks 0 and 1. I assume we need DMA support to have other banks active for buffers, directory caches, etc... ?

BTW. a long time ago I implemented the RTC direct from the **cpmsim** into the ESP32 port of the **imsaisim** because I was playing around with QDOS(?) and wanted to see if I could get timestamps on files working. It worked. So if you want to add RTC support to the CPM3 BIOS and pull that code into **imsaisim** from **cpmsim** then we'd have a working RTC.

**Comment by udo-munk** [comment]
CP/M 3 often switches to bank 0, even if this is the active bank already, adressing stuff in 0 when it could come from 0 or 1. So for best performance I only store the bank in the MMU register and then have the address logic deal with any memory access, same as real hardware does.

It is using directory buffers in bank 0. I have configured 5 pages for each of the floppy disk drives, to force the LRU cache algorithm going through all possible branches in the code. The disks have 64 directory entries with 32 bytes, so 8 pages can keep the complete directory for a disk in cache, I'll later re-configure this. For the harddisk 50 pages are configured for directory buffers, so first access to the disk directory needs a bit. For 1024 entries with 32 bytes 128 pages memory are required. One could try that, but first directory access will be even slower then. One should run some large compile jobs on the haddisk and measure the time, to find the best configuration.

Using data buffers requires memory to memory DMA between banks, way to slow to do this with the 8080, not implemented yet, requires more fancy hardware.

As far as I know IMSAI haven't had a card with RTC, so any will do and we don't need to emulate a specific one. I'll move the RTC from cpmsim into an own I/O module, then it can be used in any machine.

**Comment by dmcnaugh** [comment]
I believe I understand the issue here, I will get around to experimenting and comparing both solutions on the ESP32 and stick with the one that gives the best performance. I suspect you have the better solution.

Meanwhile, either solution still faces the problem that was captured in Issue #34.
All uses of the `mem_base()` function are at risk of being a source of errors as this always references Bank 0. We need to review its use and make modifications to ensure it isn't a problem. Any time it is accessing memory above the bank size (48K) is OK, but below the 48K mark can be a problem depending on the intended bank.

**Comment by udo-munk** [comment]
Found the time last night to upgrade the ESP32 to v 1.5 and played a bit with CP/M 3 on the machine. Works very well and is pleasant to use, I don't think you would get an feelable effect from using my solution, but likeley one can measure a better performance. Nevertheless I would suggest to change it, because the solution I implemented works like real hardware and is easier to understand.

I'll have to completely get rid of mem_base() because that only works for a 64 KB segment. There are no fatal errors caused by this yet, so it is postphoned to when I find the time to overwork this all.
